#!/usr/bin/env bash
ARGS="--volume=80"

notification() {
    dunstify "Radio set to: " "$@" -i mpv
}

menu() {
    printf "Quit\n"
    printf "1. Lofi Girl\n"
    printf "2. Chillhop\n"
    printf "3. Box Lofi\n"
    printf "4. The Bootleg Boy\n"
    printf "5. Radio Spinner\n"
    printf "6. SmoothChill\n"
    printf "7. Sanctuary Radio\n"
    printf "8. Sanctuary Radio Retro\n"
    printf "9. HardcorePower\n"
    printf "10. Synthetic FM\n"
    printf "11. Zeno [EBM Radio]\n"
    printf "12. Zeno [Futurepop]\n"
    printf "13. Zeno [Classical]\n"
    printf "14. Zeno [ClassicalFM]"
}

main() {
    choice=$(menu | rofi -dmenu | cut -d. -f1) || exit

    case $choice in
        Quit)
            dunstify "Closing rofi-radio" "Good-bye!" -i mpv
            pkill -f radio-mpv
            exit
            ;;
        1)
            pkill -f radio-mpv || echo "radio-mpv not running"
            notification "Lofi Girl ☕️🎶";
            URL="https://play.streamafrica.net/lofiradio"
            mpv $ARGS --title="radio-mpv" $URL
            break
            ;;
        2)
            pkill -f radio-mpv || echo "radio-mpv not running"
            notification "Chillhop ☕️🎶";
            URL="http://stream.zeno.fm/fyn8eh3h5f8uv"
            mpv $ARGS --title="radio-mpv" $URL
            break
            ;;
        3)
            pkill -f radio-mpv || echo "radio-mpv not running"
            notification "Box Lofi ☕️🎶";
            URL="http://stream.zeno.fm/f3wvbbqmdg8uv"
            mpv $ARGS --title="radio-mpv" $URL
            break
            ;;
        4)
            pkill -f radio-mpv || echo "radio-mpv not running"
            notification "The Bootleg Boy ☕️🎶";
            URL="http://stream.zeno.fm/0r0xa792kwzuv"
            mpv $ARGS --title="radio-mpv" $URL
            break
            ;;
        5)
            pkill -f radio-mpv || echo "radio-mpv not running"
            notification "Radio Spinner ☕️🎶";
            URL="https://live.radiospinner.com/lofi-hip-hop-64"
            mpv $ARGS --title="radio-mpv" $URL
            break
            ;;
        6)
            pkill -f radio-mpv || echo "radio-mpv not running"
            notification "SmoothChill ☕️🎶";
            URL="https://media-ssl.musicradio.com/SmoothChill"
            mpv $ARGS --title="radio-mpv" $URL
            break
            ;;
        7)
            pkill -f radio-mpv || echo "radio-mpv not running"
            notification "Sanctuary Radio ☕️🎶";
            URL="https://ssl.shoutcaststreaming.us:8090/stream"
            mpv $ARGS --title="radio-mpv" $URL
            break
            ;;
        8)
            pkill -f radio-mpv || echo "radio-mpv not running"
            notification "Sanctuary Radio Retro ☕️🎶";
            URL="https://ssl.shoutcaststreaming.us:8090/stream2"
            mpv $ARGS --title="radio-mpv" $URL
            break
            ;;
        9)
            pkill -f radio-mpv || echo "radio-mpv not running"
            notification "HardcorePower ☕️🎶";
            URL="https://panel.beheerstream.com:2199/tunein/hardcorep.pls"
            mpv $ARGS --title="radio-mpv" $URL
            break
            ;;
        10)
            pkill -f radio-mpv || echo "radio-mpv not running"
            notification "Synthetic FM ☕️🎶";
            URL="http://stream.syntheticfm.com:2199/tunein/syntheticfm.pls"
            mpv $ARGS --title="radio-mpv" $URL
            break
            ;;
        11)
            pkill -f radio-mpv || echo "radio-mpv not running"
            notification "Zeno [EBM Radio] ☕️🎶";
            URL="https://zeno.fm/radio/ebm-radio/"
            mpv $ARGS --title="radio-mpv" $URL
            break
            ;;
        12)
            pkill -f radio-mpv || echo "radio-mpv not running"
            notification "Zeno [Futurepop] ☕️🎶";
            URL="https://zeno.fm/radio/futurepop-and-synthpop-radio/"
            mpv $ARGS --title="radio-mpv" $URL
            break
            ;;
        13)
            pkill -f radio-mpv || echo "radio-mpv not running"
            notification "Zeno [Classical] ☕️🎶";
            URL="https://zeno.fm/radio/radio-christmas-non-stop-classical/"
            mpv $ARGS --title="radio-mpv" $URL
            break
            ;;
        14)
            pkill -f radio-mpv || echo "radio-mpv not running"
            notification "Zeno [ClassicalFM] ☕️🎶";
            URL="https://zeno.fm/radio/classicalfm/"
            mpv $ARGS --title="radio-mpv" $URL
            break
            ;;
    esac
}

main
