#!/bin/sh
swaybg -i $(find ~/media/images/wallpapers/ -type f | shuf -n1) -m fill &
OLD_PID=$!
while true; do
    sleep 600
    swaybg -i $(find ~/media/images/wallpapers/ -type f | shuf -n2) -m fill &
    NEXT_PID=$!
    sleep 5
    kill $OLD_PID
    OLD_PID=$NEXT_PID
done
